### ISSUE TITLE
(RTSLORD) - T-LoRD Issues

### ISSUE THREAD

**Issue by dlightman311** [enusbaum/MBBSEmu#49] opened 2020-08-21 20:53 UTC
1) Selecting Converse with patrons from the Inn locks up but does not crash MBBSEmu. After this occurs MBBSEmu still accepts connections but does not negotiate IAC or do anything other than log "HostProcess.MbbsHost.AddSession Session x.x.x.x:yyyyy added to incoming queue" until it is restarted.

2) There is no way to exit live chat (Jabber with the locals) or view the help menu. Chat doesn't work and randomly a new chat message clears the screen:

![image](https://user-images.githubusercontent.com/40728931/90934059-a63cec00-e3ce-11ea-9e75-5a411ed6f22a.png)

3) Write mail command cannot find any user specified.

4) List warriors has odd characters in the Mastered column:

![image](https://user-images.githubusercontent.com/40728931/90934087-b359db00-e3ce-11ea-8a47-01f5691fc118.png)

5) Random characters such as shown in the list warriors screen shot are output during play sometimes they are accompanied by a screen clear.

Fighting, healing, buying/selling, bank deposit/withdraw, buying a room, flirting with violet/hearing seth all work. Longer play will be required but it seems close to being 100%.

**Comment by ryanfantus** [comment] 2020-08-24 02:30
Additionally, (O)ther places from main menu doesn't respond to any keypresses other than to return, in spite of the fact that I have an IGM installed and listed there. Whether or not I installed the IGM correctly is another story. :)

**Comment by enusbaum** [comment] 2020-08-31 22:49
I believe these should now be fixed in an upcoming pull request. 

1. Caused by `strcpy()` not copying `\0` to destination when the source was null. This caused an infinite loop in the routine that generated the initial `BAR.TXT` when it needed to be created on first run.
2. This now also appears fixed
![image](https://user-images.githubusercontent.com/1139047/91775801-fc254700-ebb9-11ea-9abb-625e116cb752.png)

Please verify 3,4,5 are fixed as well on boards with more characters.

**Closed** 2020-09-01 10:47 UTC
Labels: bug, module
