### ISSUE TITLE
CMD.exe -console ANSI is weird

### ISSUE THREAD

**Issue by Cthulhuhost** [enusbaum/MBBSEmu#230] opened 2020-10-29 02:10 UTC
* Module Name Muicyber
* Version v1.0-alpha-101420

**Describe the bug**
See image. First screen (login screen of mbbs) ansi is all wonky.

**To Reproduce**
run cmd.exe
execute 'mbbsemu.exe -M Muicyber -Console'
See the login screen
https://imgur.com/WSqC2yq

**Expected behavior**
A readable login screen for human eyes would be nice.

**Screenshots**
https://imgur.com/WSqC2yq
vs
https://www.mbbsemu.com/images/login.png

Screen shots of expected vs. actual between MBBSEmu and MajorBBS/Worldgroup help with understanding the expected difference between the two.

**Software Information:**
- OS: Windows 10
- Telnet Client -Console

**Comment by enusbaum** [comment] 2020-10-29 02:24
Based on the screen shot it looks like the Unicode mapping for the ANSI characters is working as intended, but the ANSI CSI codes aren't being handled by the console for color/position.

We'll need to check to see if there's a way for us to set the terminal/console to color mode in addition to Unicode.

**Comment by enusbaum** [comment] 2020-10-31 16:49
It looks like for Windows, we need to enable `ENABLE_VIRTUAL_TERMINAL_PROCESSING`

https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences?redirectedfrom=MSDN

I'm looking into how we can do this programmatically within the Application if the end user is on a Win32 platform.

**Comment by enusbaum** [comment] 2020-10-31 17:07
Confirmed a fix for this by detecting Windows platforms and setting the proper flags for the current console. 

PR pending

![image](https://user-images.githubusercontent.com/1139047/97785222-152a8400-1b7a-11eb-8198-4fa2e91a0bcf.png)

**Closed** 2020-10-31 17:16 UTC
Labels: bug
