### ISSUE TITLE
[ELWMM] Mud Magic - Crashes when entering module

### ISSUE THREAD

**Issue by tuday2** [enusbaum/MBBSEmu#129] opened 2020-09-15 03:17 UTC
**Module Information**
* Identifier: ELWMM
* Module Name: Mud Magic
* Version: 1.22

**Describe the bug**
Crashes when entering module

**To Reproduce**
1. Add module to moduleConfig.json
2. Load MBBSEmu
3. Enter Mud Magic module

**Expected behavior**
Enter and play game

**Screenshots**
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '1547' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at MBBSEmu.Memory.MemoryCore.GetInstruction(UInt16 segment, UInt16 instructionPointer)
   at MBBSEmu.HostProcess.ExecutionUnits.ExecutionUnit.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.Module.MbbsModule.Execute(IntPtr16 entryPoint, UInt16 channelNumber, Boolean simulateCallFar, Boolean bypassSetState, Queue`1 initialStackValues, UInt16 initialStackPointer)
   at MBBSEmu.HostProcess.MbbsHost.WorkerThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

**Software Information:**
- OS: Windows 2019 Server Standard
- Telnet Client: NetRunner

**Comment by enusbaum** [comment] 2020-09-15 23:03
This looks like an opcode issue where it's jumping to an invalid location.

**Comment by enusbaum** [comment] 2020-09-15 23:44
This was caused by the processing of `TEXT_VARIABLES`. Because Execution Units share the same memory space, and the stack is universally segment zero. Because the base pointer has a chance of overlapping with the calling EU, we manually decrement the stack pointer 3k to avoid any overlap.

While this was fixed in FSD, the same fix wasn't implemented with `TEXT_VARIABLES`.

**Closed** 2020-09-16 16:56 UTC
Labels: bug
