### ISSUE TITLE
[MBBSEmu] MBBSEmu - Telix spits out ± when connecting to MBBSEmu

### ISSUE THREAD

**Issue by brianmiller** [enusbaum/MBBSEmu#255] opened 2020-11-05 04:02 UTC
**Module Information**
* Identifier [MBBSEmu]
* Module Name [MBBSEmu]
* Version [110220-2]

**Describe the bug**
When connecting to MBBSEmu using Telix via DOSBox the "±" character repeats itself over and over. This doesn't happen with any other BBS. I've attached screenshots as well.  This may not be a bug but maybe good for awareness or maybe a solicitation for guidance. 

**To Reproduce**
1. Connect to MBBSEmu with Telix

**Expected behavior**
Not repeating the "±" character.

**Screenshots**
![Screenshot from 2020-11-04 20-01-57](https://user-images.githubusercontent.com/342276/98196313-a5e5c480-1ed8-11eb-9dc9-47819930e22c.png)
![Screenshot from 2020-11-04 20-02-14](https://user-images.githubusercontent.com/342276/98196314-a67e5b00-1ed8-11eb-8932-432a6a340c3a.png)

**Software Information:**
- OS: [Fedora 32]
- Telnet Client [Telix via DOSBox]

**Comment by paladine** [comment] 2020-11-05 04:18
This is likely a duplicate of issue #248, and is being worked on now.

**Comment by brianmiller** [comment] 2020-11-05 04:20
You guys are killing it.  I'm a Patreon now!

**Closed** 2020-11-06 02:45 UTC
